spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydatabase
    username: root
    password: mysecretpassword
  jpa:
    show-sql: true
    properties:
      hibernate:
        "[format_sql]": true
  data:
    web:
      pageable:
        page-parameter: pagina
        size-parameter: tamanho
        sort-parameter: ordem
server:
  error:
    include-stacktrace: never